FROM docker.elastic.co/beats/filebeat:7.3.2
COPY filebeat.yml /usr/share/filebeat/filebeat.yml
COPY apache.log  /tmp/filebeat/apache.log
USER root
RUN chown root:filebeat /usr/share/filebeat/filebeat.yml
RUN chmod 640 /usr/share/filebeat/filebeat.yml
USER filebeat
EXPOSE 80 443