---

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
      - /tmp/filebeat/apache.log 
output.logstash:
  hosts: ["logstash:5000"]

  
